project 'BabySelfie.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BabySelfie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BabySelfie
  pod 'CircleSlider'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'Fabric'
  pod 'Crashlytics'

end
