# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!
pod 'Firebase', '>= 2.5.1'
pod 'IQKeyboardManagerSwift', '3.3.4'
pod 'CircleSlider'
pod 'SwiftLoader'

target 'BabySelfie' do

end

